(FACT-2809) Fixed output differences on solaris
puppetlabs/facter pull request #2116
Opened 2020-10-01 16:12 UTC by sebastian-miclea

After running the tests that compares output between Facter3 and Facter4 we've noticed some differences.
The differences were in: mountpoints (some were skipped), zones (count) and mtu.

2020-10-01 16:40 UTC, sebastian-miclea commented
Jenkins please test this on all

2020-10-02 00:00 UTC, puppetcla commented
CLA signed by all contributors.

2020-10-06 11:27 UTC, Filipovici-Andrei requested changes

2020-10-06 11:27 UTC, Filipovici-Andrei commented on lib/facter/resolvers/solaris/mountpoints.rb
> +            @fact_list[:mountpoints] = mounts
We should return @fact_list[fact_name]

2020-10-06 11:27 UTC, Filipovici-Andrei commented on lib/facter/resolvers/solaris/mountpoints.rb
> +          def read_mounts # rubocop:disable Metrics/AbcSize
We should split this method to avoid disabling rubocop

2020-10-09 12:19 UTC, Filipovici-Andrei approved these changes

2020-10-09 12:20 UTC, merged