(FACT-2857) Added acceptance test for user query scenario
puppetlabs/facter pull request #2197
Opened 2020-11-24 21:26 UTC by sebastian-miclea

2020-12-15 13:42 UTC, IrimieBogdan commented on acceptance/tests/options/config_file/ttls_cached_custom_and_core_fact.rb
> +        assert_equal(custom_fact_value, cache[custom_fact_name])
We should also check that the core fact did not get cached at this step

2020-12-15 13:42 UTC, IrimieBogdan commented on acceptance/tests/options/config_file/ttls_cached_custom_and_core_fact.rb
> +      step "custom fact value is correct" do
This step checks core values, the description should be renamed to `core fact value is correct`

2020-12-15 13:42 UTC, IrimieBogdan commented on acceptance/tests/options/config_file/ttls_cached_custom_and_core_fact.rb
> +        assert_equal(core_value, cache[core_fact_name].to_s)
We should check that the custom facts is not in the cache file at this step.

2020-12-15 13:42 UTC, IrimieBogdan commented on acceptance/tests/options/config_file/ttls_cached_custom_and_core_fact.rb
> +test_name 'missing facts should not invalidate cache' do
The test does not cover all the cases from FACT-2857 description.
The test should
- check we can cache a fact
- check that when we query the second time for the same fact we get the fact value from the cache
- request to_hash
- check that the cache is no longer changed, no matter what fact we ask for

2020-12-18 14:19 UTC, Filipovici-Andrei requested changes

2020-12-18 14:19 UTC, Filipovici-Andrei commented on acceptance/tests/options/config_file/ttls_cached_custom_and_core_fact.rb
> +        assert_equal(core_value, cache[core_fact_name])
Here you should check that the cached value coincides with the one retrieved in the first request. Making the check like this, you can't be sure that facter doesn't simply solve the core fact again and rewrites the cache file.

2021-01-12 09:00 UTC, Filipovici-Andrei approved these changes

2021-01-27 06:57 UTC, merged