(FACT-2944)Facter fails retrieving fqdn with jruby
puppetlabs/facter pull request #2296
Opened 2021-02-26 10:28 UTC by oanatmaria

2021-02-26 10:29 UTC, oanatmaria commented
jenkins please test this,puppet-agent,puppet on all

2021-03-02 10:34 UTC, oanatmaria commented
jenkins please test this,puppet-agent,puppet on all

2021-03-02 14:17 UTC, Filipovici-Andrei requested changes

2021-03-02 14:17 UTC, Filipovici-Andrei commented on spec/facter/resolvers/linux/hostname_spec.rb
> +          expect(hostname_resolver.resolve(:hostname)).to eql(hostname)
Is there a reason to use `eql` instead of `eq`? Something to do with the type conversions done by `eq`

2021-03-02 14:17 UTC, Filipovici-Andrei commented on spec/facter/resolvers/linux/hostname_spec.rb
> +        it 'detects hostname' do
You are performing the exact same checks in every scenario. I think that adding these three checks inside a shared_example would greatly improve readability of the different scenarios.

2021-03-03 13:38 UTC, oanatmaria commented
All acceptance tests passed: https://jenkins-platform.delivery.puppetlabs.net/job/platform_puppet-agent-extra_puppet-agent-integration-suite_pr/2091/

2021-03-03 14:20 UTC, Filipovici-Andrei commented on spec/facter/resolvers/linux/hostname_spec.rb
> +              expect(hostname_resolver.resolve(:domain)).to be_nil
for this context you could add let(:domain) { nil } and use the shared_examples

2021-03-03 14:24 UTC, Filipovici-Andrei commented on spec/facter/resolvers/linux/hostname_spec.rb
> +        let(:host) { "#{hostname}.#{domain}" }
setting the `host` variable here, doesn't it mean that ruby socket hostname method works?

2021-03-03 14:30 UTC, Filipovici-Andrei commented on spec/facter/resolvers/linux/hostname_spec.rb
> +              expect(hostname_resolver.resolve(:domain)).to be_nil
for this context you could add let(:domain) { nil } and use the shared_examples

2021-03-03 15:36 UTC, florindragos approved these changes
LGTM

2021-03-04 16:43 UTC, Filipovici-Andrei approved these changes

2021-03-04 16:54 UTC, merged